export default {
    ACTIVE_LANGUAGE: "CURRENT_ACTIVE_LANGUAGE",

    UPDATE_NOTIFICATIONS_COUNTER: "UPDATE_NOTIFICATIONS_COUNTER",
    RESET_NOTIFICATIONS_COUNTER: "RESET_NOTIFICATIONS_COUNTER",

    UPDATE_CART: "UPDATE_CART",
    UPDATE_CART_INDEX: "UPDATE_CART_INDEX",
    UPDATE_CURRENCY: "UPDATE_CURRENCY",
    RESET_CART: "RESET_CART",
    DELETE_CART_ITEM: "DELETE_CART_ITEM",

    UPDATE_PROFILE: "UPDATE_PROFILE",
    RESET_PROFILE: "RESET_PROFILE"
}